name: Bundle and deploy on GitHub Pages

on:
  push:
    branches:
      - master

permissions:
  contents: write
  pages: write

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install

      - name: Run eslint checks
        run: npm run lint

      - name: Run stylelint checks
        run: npm run lint:css
      
      - name: Run svelte-check
        run: npm run check
  build:
    runs-on: ubuntu-latest
    needs: check
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install

      - name: Build project
        env:
          BASE_PATH: '/${{ github.event.repository.name }}'
        run: npm run build
      
      - name: Exclude unwanted files
        run: |
          rm -rf .github
          rm -rf .gitignore
          rm -rf .stylelintignore
          rm -rf .stylelintrc.json
          rm -rf eslint.config.js
          rm -rf package.json
          rm -rf package-lock.json
          rm -rf rollup.config.js
          rm -rf tsconfig.json

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4